version: '3.2'

services:
  swarmui:
    volumes:      
      - /var/run/docker.sock:/var/run/docker.sock
      - ./swarmui_data:/data
    image: puskartrital/swarmui:linux-amd64-latest
    ports:
      - "9000:9000"
      - "8000:8000"
    
    networks:
      - agent_network

networks:
  agent_network:


volumes:
  portainer_data:      
      